version: '3.8'

services:
  dashboard:
    build: .
    container_name: skin_shop_dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./crawler.log:/app/crawler.log                     # Persist logs
    env_file:
      - .env
    restart: "always"
